installRequiredPythonLibraries: false
approveManualInstallPlanViaHook: true

installPlanApproverAndVerifyJobsImage: quay.io/trevorbox/installplanapproverandverifier:4.16.0 # quay.io/openshift/origin-cli:4.16

operatorGroups:
- name: metallb-system
  createNamespace: true

operators:
- channel: stable
  installPlanApproval: Manual
  name: metallb-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # csv: kiali-operator.v2.17.1
  namespace: metallb-system
  installPlanVerifierActiveDeadlineSeconds: 1200
