---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/istio-system-configs
  - authorizationpolicy-allow-nothing-istio-waypoint.yaml

# patches:
#   - path: patch-delete-peerauthentication-default.yaml
