apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample

helmCharts:
- name: curl
  repo: https://trevorbox.github.io/helm-charts
  namespace: sample
  version: ~0.0.2
  releaseName: curl

resources:
  - netoworkpolicies.yaml
