apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
spec:
  nodeDisruptionPolicy:
    units:
      - name: myscript.service
        actions:
          - type: Reload
            reload:
              serviceName: myscript.service
          - type: DaemonReload
          - type: Restart
            restart:
              serviceName: myscript.service