apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
spec:
  nodeDisruptionPolicy:
    units:
    - actions:
      # - type: Drain
      - reload:
          serviceName: myscript.service
        type: Reload
      - type: DaemonReload
      - restart:
          serviceName: myscript.service
        type: Restart
      name: myscript.service