apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
spec:
  nodeDisruptionPolicy:
    # files:
    #   - actions:
    #     - restart:
    #         serviceName: myscript.service
    #       type: Restart
    #     path: /usr/local/bin/myscript.sh
    units:
      - name: myscript.service
        actions:
          - type: Reload
            reload:
              serviceName: myscript.service
          - type: DaemonReload
          - type: Restart
            restart:
              serviceName: myscript.service