apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
spec:
  nodeDisruptionPolicy:
    units:
    - actions:
      - reload:
          serviceName: myscript.service
        type: Reload
      - type: DaemonReload
      - restart:
          serviceName: myscript.service
        type: Restart
      name: myscript.service
    - actions:
      - restart:
          serviceName: myscript.timer
        type: Restart
      name: myscript.timer
    files:     
    - actions:
      - reload:
          serviceName: myscript.service
        type: Reload
      - type: DaemonReload
      - restart:
          serviceName: myscript.service
        type: Restart
      path: /usr/local/bin/myscript.sh
