features:
  stable:
    host: golang-ex-stable-istio-ingress.apps.sandbox3242.opentlc.com
  high:
    host: golang-ex-high-istio-ingress.apps.sandbox3242.opentlc.com
  featurea:
    host: golang-ex-featurea-istio-ingress.apps.sandbox3242.opentlc.com
