apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: istio-ingress
  # annotations:
  #   cert-manager.io/issuer: internal-issuer
spec:
  gatewayClassName: istio
  listeners:
  - name: https-httpbin
    hostname: "httpbin.example.com"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: In
              values:
                - httpbin
                - nginx-echo-headers
    # allowedRoutes:
    #   namespaces:
    #     from: All
    tls:
      mode: Terminate
      certificateRefs:
      - group: ''	
        kind: Secret
        name: httpbin-gateway-cert
  - name: https-nginx-echo-headers
    hostname: "nginx-echo-headers.example.com"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - group: ''	
        kind: Secret
        name: nginx-echo-headers-gateway-cert
  infrastructure:
    annotations:
      some-key: some-value
    labels:
      key: value
    parametersRef:
      group: ""
      kind: ConfigMap
      name: ingress-gateway-params
