apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-echo-headers-ingress
  namespace: nginx-echo-headers
spec:
  hostnames:
    - nginx-echo-headers.example.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ingress-gateway
      namespace: istio-ingress
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: nginx-echo-headers
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
