kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: example-routes
  namespace: istio-ingress
  annotations:
    route.openshift.io/termination: "passthrough"
  #   route.openshift.io/insecureEdgeTerminationPolicy: redirect
spec:
  rules:
    - host: httpbin.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ingress-gateway-istio
                port:
                  number: 443

    # - host: nginx-echo-headers.example.com
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: ingress-gateway-istio
    #             port:
    #               number: 443