apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate-httpbin-gateway-cert.yaml
- certificate-nginx-echo-headers-gateway-cert.yaml
- configmap-ingress-gateway-params.yaml
- gateway-ingress-gateway.yaml
- httproute-httpbin-istio-ingress.yaml
- httproute-nginx-echo-headers-ingress.yaml
- networkpolicy-ingress-gateway-allow-external.yaml
- ingress-example-routes.yaml
