apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-egress-gateway.yaml
  - serviceentry-httpbin-org.yaml
  - serviceentry-www-google-com.yaml
  - authorizationpolicy-www.google.com.yaml