apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-egress

resources:
  - gateway-egress-gateway.yaml
  - serviceentry-httpbin-org.yaml
  - serviceentry-www-google-com.yaml
  - authorizationpolicy-www.google.com.yaml
  - serviceentry-login-microsoftonline-com.yaml
  - serviceentry-graph-microsoft-com.yaml
  - authorizationpolicy-login-microsoftonline-com.yaml
  - authorizationpolicy-graph-microsoft-com.yaml
