apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-httpbin.yaml
  - gateway-httpbin-gateway.yaml
  - gateway-httpbin-waypoint.yaml
  - httpbin.yaml
  - httproute-httpbin-ingress.yaml
  - httproute-httpbin-waypoint-route.yaml

patches:
- options: add
  path: /metadata/labels/istio.io%2Fuse-waypoint
  value: httpbin-waypoint
