apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: httpbin

resources:
  - gateway-httpbin-gateway.yaml
  - gateway-httpbin-waypoint.yaml
  - httpbin.yaml
  - httproute-httpbin-ingress.yaml
  - httproute-httpbin-waypoint-route.yaml
  - networkpolicy-httpbin-allow-external.yaml
