apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin-istio-ingress
  namespace: authz-custom
spec:
  hostnames:
    - httpbin.example.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ingress-gateway
      namespace: istio-ingress
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: oauth2-proxy
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /oauth2
