apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: oauth2-proxy
  repo: https://oauth2-proxy.github.io/manifests
  valuesFile: values.yaml
  namespace: authz-custom
  version: 8.5.0
  releaseName: oauth2-proxy

resources:
  - auth
  - httproute-httpbin-istio-ingress.yaml

patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
    name: oauth2-proxy
