apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: oauth2-proxy
  repo: https://oauth2-proxy.github.io/manifests
  valuesFile: values.yaml
  namespace: test
  version: 8.5.0
  releaseName: oauth2-proxy

resources:
  # - certificate-oauth-bookinfo-cert.yaml
  # - gateway-oauth-bookinfo.yaml
  - route-test.yaml
  - namespace-test.yaml
  # - secret-oauth2-proxy.yaml
  # - serviceentry-auth0.yaml
  # - virtualservice-oauth-bookinfo.yaml
  - auth

patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
    name: oauth2-proxy
